const fs = require('fs');
const path = require('path');

const envContent = `// Auto-generated by Netlify build script
window.ENV = {
    GEMINI_API_KEY: "${process.env.GEMINI_API_KEY || ''}",
    FIREBASE_API_KEY: "${process.env.FIREBASE_API_KEY || ''}",
    FIREBASE_AUTH_DOMAIN: "${process.env.FIREBASE_AUTH_DOMAIN || ''}",
    FIREBASE_PROJECT_ID: "${process.env.FIREBASE_PROJECT_ID || ''}",
    FIREBASE_STORAGE_BUCKET: "${process.env.FIREBASE_STORAGE_BUCKET || ''}",
    FIREBASE_MESSAGING_SENDER_ID: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
    FIREBASE_APP_ID: "${process.env.FIREBASE_APP_ID || ''}",
    FIREBASE_MEASUREMENT_ID: "${process.env.FIREBASE_MEASUREMENT_ID || ''}",
    IMAGEKIT_URL: "${process.env.IMAGEKIT_URL || ''}",
    IMAGEKIT_PUBLIC_KEY: "${process.env.IMAGEKIT_PUBLIC_KEY || ''}",
    IMAGEKIT_PRIVATE_KEY: "${process.env.IMAGEKIT_PRIVATE_KEY || ''}"
};
`;

const destPath = path.join(__dirname, '../js/env.js');

try {
    fs.writeFileSync(destPath, envContent);
    console.log('Successfully generated js/env.js from Netlify environment variables.');
} catch (error) {
    console.error('Error generating js/env.js:', error);
    process.exit(1);
}
